/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'THICCCBOI', 'sans-serif'],
      },
      screens: {
        'mobile-small': '479px',
        mobile: '480px',
        tablet: '768px',
        laptop: '1024px',
        desktop: '1440px',
        monitor: '2560px',
      },
      spacing: {
        0.25: '0.25rem',
        0.75: '0.75rem',
        1.25: '1.25rem',
        1.75: '1.75rem',
        2.25: '2.25rem',
        2.75: '2.75rem',
        3.25: '3.25rem',
        3.75: '3.75rem',
        4.25: '4.25rem',
        4.75: '4.75rem',
        5.25: '5.25rem',
        5.75: '5.75rem',
        6.25: '6.25rem',
        6.75: '6.75rem',
        7.25: '7.25rem',
        7.75: '7.75rem',
        8.25: '8.25rem',
        8.75: '8.75rem',
        9.25: '9.25rem',
        9.75: '9.75rem',
        10.25: '10.25rem',
        10.75: '10.75rem',
        11.25: '11.25rem',
        11.75: '11.75rem',
        12.25: '12.25rem',
        12.75: '12.75rem',
        13.25: '13.25rem',
        13.75: '13.75rem',
        14.25: '14.25rem',
        14.75: '14.75rem',
        15.25: '15.25rem',
        15.75: '15.75rem',
        16.25: '16.25rem',
        16.75: '16.75rem',
        17.25: '17.25rem',
        17.75: '17.75rem',
        18.25: '18.25rem',
        18.75: '18.75rem',
        19.25: '19.25rem',
        19.75: '19.75rem',
        20.25: '20.25rem',
        20.75: '20.75rem',
        21.25: '21.25rem',
        21.75: '21.75rem',
        22.25: '22.25rem',
        22.75: '22.75rem',
        23.25: '23.25rem',
        23.75: '23.75rem',
      },
      zIndex: {
        modal: '100',
        drawer: '50',
        floating: '40',
        header: '30',
        footer: '20',
        front: '10',
        default: '1',
        background: '-10',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        '2xs': 'var(--shadow-2xs)',
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
      },
    },
  },
  plugins: [],
};
